### ISSUE TITLE
Consistent and standard error propagation

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#1439]
### Scenario
We have different and multi level hierarchies of modules, helpers, logic etc. And each interface layer e.g. “API”, “Websocket” is consuming those modules individually. 

Considering that some error been propagated from an underlying module and catched by “API” or “Websocket” or even on domain level catched by “process”. So we need to answer to these questions. 

- Categorically what type of error it is? 
- What need to be done with this error? 
- If interfered by HTTP Layer what status code to respond? 
- If interfered by websocket, what response need to send? 
- If logging required, what level of logging is appropriate for this error?

Currently we are dealing with all these questions on adhoc basis with redundant code. That cause instability and increase complexity in code. 

### Case Study
Suppose we this method was called 
```
logic.accounts.getAll 
```
With some parameters and in case of any error it is throwing error
```
setImmediate(cb, 'Account#getAll error');
```
Suppose this error catched on API layer, we are not sure its an SQL related error. All we can do is to add condition if(error === “Account#getAll error”) then decide to respond with 500 error code. But such if such SQL error generated by other module with different message, then we have to extend that condition. 

And if some one change the error message, all error catching logic will break. 

### Proposed Solution
So hereby I propose to introduce custom error constructors introduced and used consistently in every place of the application. Those error constructors can have different embed information on definition level, so our interface layers can catch and process those consistently. 

```js
var SQLError = function(message) {
  Error.captureStackTrace(this, this.constructor);
  this.message = message; 
  
  this.httpStatusCode = 500;
  this.log = true;
  this.logLevel = 'debug';
};
SQLError.prototype = new Error();


var ParamValidationError = function(param, message) {
  Error.captureStackTrace(this, this.constructor);
  this.param = param
  this.message = message; 
  
  this.httpStatusCode = 400;
  this.log = true;
  this.logLevel = 'info';
};
ParamValidationError.prototype = new Error();

var RecordNotFoundError = function(message) {
  Error.captureStackTrace(this, this.constructor);
  this.message = message; 
  
  this.httpStatusCode = 404;
  this.log = false;
};
ParamValidationError.prototype = new Error();

module.exports = {
  SQLError: SQLError,
  ParamValidationError: ParamValidationError,
  RecordNotFoundError: RecordNotFoundError
};
```

**Comment by jondubois** [comment]
@nazarhussain :+1: I used a similar approach in SocketCluster (https://github.com/SocketCluster/sc-errors/blob/master/index.js) and it's great.

For inheritance, instead of `SQLError.prototype = new Error();` you can also use:

```js
SQLError.prototype = Object.create(Error.prototype);
```

^ but it's the same principle.

Also it's good if we can make it so that every error in the system has at least one property in common which we can use to consistently check the error type (regardless of where or how the error occurred). In SC, I used the `name` (string) property for this. A general-purpose `code` property is sometimes also used.

**Comment by vitaly-t** [comment]
Many examples of how `pg-promise` does it: https://github.com/vitaly-t/pg-promise/tree/master/lib/errors

**Comment by shuse2** [comment]
Two points to add to this discussion.
- Use of array of errors.
I think this should be avoided although we use intensively in the transaction library.
This makes the error handling more complex and non-standard
- Remove usage of throw in case of expected errors
Our application needs to handle various error in different way, and we want to have consistent way of handling error. Therefore, we should consistently return error instead of throwing in case of handleable error.

**Comment by nazarhussain** [comment]
While making error propagation a standard approach we should also consider error formats. More details on this issue https://github.com/LiskHQ/lisk-sdk/issues/5432

**Comment by shuse2** [comment]
Currently, we have https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/errors.ts , which will handle the external error. We will improve in the future
