### ISSUE TITLE
Improve performance of "snapshot" and "rebuild" process

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#1843]
### Expected behavior
We are rebuilding the blockchain while taking snapshot and ore restoring it by rebuild. Actually that process should take very long time, "blockchain" verification should be done once either in snapshot process or rebuild process. 

### Actual behavior

Currently we verify each single block for first taking snapshot. Then we verify each single block again while restoring that snapshot. For main net that single side process take over 12 hours. 

### Steps to reproduce
Take snapshot with running `bash lisk_snapshot.sh` and then rebuild it by `bash lisk.sh rebuild -f `

### Which version(s) does this affect? (Environment, OS, etc...)
`1.0.0`

**Comment by webmaster128** [comment]
@nazarhussain could you point to the place in code where the blocks are verified while restoring?

In https://github.com/LiskHQ/lisk-scripts/blob/0ae84a1/packaged/lisk.sh#L146 the dump is copied back into the database but I can see no crypto happening

**Comment by webmaster128** [comment]
I wonder that the bottleneck in the verification process snapshot is (during the dump). For me it takes 10–20 seconds to verify 1000 blocks but all my 4 cores have a load of only 25 %. Is there a major IO task going on? I know that reading all required data of 1000 blocks takes ~ 1 second. But I don't understand what's happening the rest of the time.

I tried to profile the job using [simple-profiling](https://nodejs.org/en/docs/guides/simple-profiling/) but I stuck because I was not able to isolate the verification: when I want to profile only 30 rounds of blocks, the lisk node deleted every block with height >=  30*101 and this deletion consumes most of the time.

One way to profile this better could be to create a snapshot database with only a small number of rounds in it but this may also change the results.

**Comment by nazarhussain** [comment]
@webmaster128 I am pretty sure about why your 4 cores are not completely utilized. It's because of the single threaded nature of NodeJS itself. And especially the nature of operations we perform is completely sequential. We can process block with height 2 ONLY when a block with heigh 1 is completely processed. So the async power of NodeJS is not been actually utilized in our problem domain. 


Related to the first comment of your's, the snapshot verification is not initiated in the shell script, its part of the core code. I noticed this behavior as well @4miners as well. But that happens in some edge case and we have not yet identified the reason. As soon we will focus on this task, we will definitely look into further details.

**Comment by 4miners** [comment]
Yep, I think this issue is related to https://github.com/LiskHQ/lisk/issues/1781, specifically `blockId` field and check that is performed when node starts. After restoring from snapshot node should not perform rebuild (recreate "memory" tables).

About performance of snapshoting process - it can be potentially improved a little by skipping apply transactions to unconfirmed state, and instead overwrite unconfirmed states with confirmed after snapshot is finished.

**Comment by webmaster128** [comment]
@nazarhussain I know that NodeJS is a single thread environment and async does not mean multithreading. I was wondering why there is not a single core with 100% load. But this could be because the process is changing the core regularly such that I see 25 % on each core instead of 100 % on one core. Anyway, I am not a node expert and cannot really help here.

**Comment by fchavant** [comment]
@nazarhussain since testnet is running on `1.0.0-rc.1` snapshots take 22 hours (they used to take 8 hours)

**Comment by 4miners** [comment]
This issue is no longer viable because of https://github.com/LiskHQ/lisk-sdk/issues/1781, https://github.com/LiskHQ/lisk-sdk/issues/3109 and https://github.com/LiskHQ/lisk-sdk/issues/3119.
