### ISSUE TITLE
Add the version of the used core to the info of a forged Block

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk-sdk#1931]
### Expected behavior
I'd like to see with which core version a block was forged. This would allow the monitoring of how fast delegates update their nodes, and how many of the forged blocks are on the recent core version. This info could be crucial in times of immediate hot fixes because of severe security issues.
The version info could be added during the forging of the block, similar to the timestamp, who forged it, what the previous block was, etc...

### Actual behavior
It's currently not possible to see who runs which version, and how many of the blocks are forged with what version.

**Comment by webmaster128** [comment]
Good point. If that is implemented, I'd love to see a User-Agent like approach that includes a client name and version in order to support alternative 3rd party core implementations in the future. This is a step in the direction of separating protocol and implementation, which usually leads to better software – no matter if there will ever be an alternative implementation or not.

**Comment by shuse2** [comment]
This issue requires protocol change.
For further discussion, please go to https://research.lisk.io/
