### ISSUE TITLE
Convert BlockReward class methods to static methods

### ISSUE THREAD

**Issue by yatki** [LiskHQ/lisk-sdk#2412]
### Expected behavior
[block_reward.js#L35](https://github.com/LiskHQ/lisk/blob/development/logic/block_reward.js#L35) Here we don't need to have class properties. We can directly use constants in the methods.

But removing properties causes eslint exceptions (class-method-use-this).

We need to define all methods as static classes and refactor its usages.
### Actual behavior

We are using unnecessary class properties.

### Which version(s) does this affect? (Environment, OS, etc...)
1.3.0+

**Comment by MaciejBaj** [comment]
Both `REWARDS.OFFSET` and `REWARDS.DISTANCE` are already integers and the actions performed by the constructor of BlockRewards are redundant:
```
constructor() {
		// Distance between each milestone
		this.distance = Math.floor(REWARDS.DISTANCE);

		// Start rewards at block (n)
		this.rewardOffset = Math.floor(REWARDS.OFFSET);
	}
```
 Rather than converting `this.distance` and `this.rewardOffset` to static methods, we should remove the whole constructor and use `REWARDS.OFFSET` and `REWARDS.DISTANCE` constants directly in the calculations.

**Comment by yatki** [comment]
@MaciejBaj I totally agree.  What about getting rid of this class completely and just exporting functions?

**Comment by diego-G** [comment]
@MaciejBaj @yatki same happens in logics `account`, `round` and `transactions`. Why don't we tackle this as a parent issue with a proper example as template?
