### ISSUE TITLE
Add QA test for malformed peerLists

### ISSUE THREAD

**Issue by mitsujutsu** [LiskHQ/lisk-sdk#3971]
### Expected behavior

Add test to check that `lisk-p2p` properly handles `peerLists` loaded with potentially invalid `P2PPeerInfo`.

### Actual behavior

There are no QA tests for this behavior. This feature did not exist prior to v2.3.

### Which version(s) does this affect? (Environment, OS, etc...)
2.3

**Comment by ishantiw** [comment]
After testing using one of the nodes from the Alpha network and making it return malformed `peerinfo` like `broadhash` malformed of other peers and adding a field with an array of strings values. I made API calls to other nodes to check if they are showing the malformed peerInfo but it doesn’t because when we connect with any peer we update the `peerInfo` only when it is coming from that peer only. 
http://104.248.152.50:4000/api/peers?limit=100
![image](https://user-images.githubusercontent.com/9600691/63173656-9dd60680-c040-11e9-82a6-f50a5193045c.png)

As of now, we only add peers from discovery to the `PeerBook` on `connect` event and whenever we are connecting we are also updating `peerInfo` by asking the `status`. This makes it very difficult to do any IP poisoning or sending malformed peerInfo.  So the version is resilient against malformed peerInfo and Ip poisoning.
