### ISSUE TITLE
Delete caching mechanism in Dpos

### ISSUE THREAD

**Issue by yatki** [LiskHQ/lisk-sdk#4217]
### Description
We would like to remove caching mechanism and all related tests.
### Motivation

There is not much value in caching delegate list as it's just one database call to get the list now. And it just brings more complexity to the logic.

### Acceptance Criteria

- Delete caching mechanism in Dpos/DelegateList
- Delete test cases in getRoundDelegates.spec.js

**Comment by SargeKhan** [comment]
Does it make sense to do it? I am thinking about the scenario where we want to do fast chain switching. In this case, we will be required to 202 blocks before starting the synchronization. It would lead to at least 202 database calls, when all these calls can easily be cached. The result - as it has already been done before, can be stored in the memory. What do you think @shuse2

**Comment by shuse2** [comment]
It is true that we need to do 202 DB calls, but since we are processing one by one, most likely it would be fine imo. It is a DB call with primary key per block, which shouldn't be a problem.
We might add some performance gain, but it will increase the complexity especially with 2 rounds before logic. We should optimize it when we need to.
