### ISSUE TITLE
Request nodeInfo from outbound peers before adding to peer lists

### ISSUE THREAD

**Issue by mitsuaki-u** [LiskHQ/lisk-sdk#4260]
### Description

Upon outbound connections, a lisk node should request `nodeInfo`:`protocolVersion` to see if it is compatible before adding to peer lists. If compatible, add to relevant peer lists. If the version is not compatible, it should disconnect the peer.

### Motivation

Handshake checks minimum `protocolVersion` for inbound peers but not outbound. Currently there is no way to limit outbound connected peers by checking the `protocolVersion`. 

### Acceptance Criteria

Proper functionality implemented in `p2p` and `peerPool`.

**Comment by alepop** [comment]
`procotoclVersion` is checked on `connection` state but not on `handshake` state as you wrote
https://github.com/LiskHQ/lisk-sdk/blob/16cba4e0556b7a5ab2048c5e047f82bf44590f67/elements/lisk-p2p/src/p2p.ts#L683
this validation is handled by this event:
https://github.com/LiskHQ/lisk-sdk/blob/16cba4e0556b7a5ab2048c5e047f82bf44590f67/elements/lisk-p2p/src/p2p.ts#L577

However SocketCluster provides the `handshake` event and I think it's better to move logic to validate `protocolVersion` to this part. @jondubois am I right?

**Comment by mitsujutsu** [comment]
@alepop You are correct in that `_peerHandshakeCheck` is called on the `connection` event (when an inbound peer connects to a node). It is done this way since we receive the `nodeInfo` required for a handshake when `inbound` peers connect to a receiving node. For `outbound` connections we initially only have the `ipAddress` and `wsPort` so we need to request the information required. This issue is more about this distinction. Please feel free to raise a separate issue regarding your recommendation to move logic to the SocketCluster `handshake` event.

**Comment by alepop** [comment]
@mitsujutsu `handshake` error by socket server can pass custom error code to a client when connection is killed. So in that case we can handle this specific error code (like protocolVersion is invalid) and ban that node, and you don't need any specific request to detect peer protocol version for outbound connection.

**Comment by jondubois** [comment]
@alepop It's possible using query parameters in the WebSocket handshake and can allow the protocolVersion to be detected a few milliseconds sooner. But currently we don't use the SC handshake event because it adds another layer of complexity if we need to handle an additional case that the inbound peer can be in a 'connecting' state. Right now we have the benefit that inbound peers are always in a connected state by the time they're created so we know it's safe to send messages to them. It's better if we don't manage pending inbound sockets outside of the Peer instance either.

The benefit of this seems minor. Also the peer should not be able to spam the socket before they complete the handshake now because SC will disconnect immediately.
