### ISSUE TITLE
Advanced test coverage related to inbound eviction

### ISSUE THREAD

**Issue by jondubois** [LiskHQ/lisk-sdk#4280]
### Description

More tests are needed to verify that inbound peer eviction is working under unusual scenarios.
Some things to check (note that this is not an exhaustive list):

- Verify that many bad peers connecting to a node quickly will not cause all good peers to be evicted.
- Verify that old version peers are not given more protection than new version peers.

Related issue: https://github.com/LiskHQ/lisk-sdk/issues/4229

### Motivation

Inbound peer eviction/protection is a complex feature which requires more thorough testing.

### Acceptance Criteria

- The test cases cover advanced or malicious scenarios like the ones described above.
- The goal of this issue is not to add test cases to verify obvious functionality. The tests should aim to uncover flaws. They need to focus on edge cases.

**Comment by mitsujutsu** [comment]
Regarding `Verify that old version peers are not given more protection than new version peers.`:  This is an emergent consequence of intended behavior, since old version nodes using full mesh protocol will try to connect to all peers resulting in them connecting earlier. The eviction process intentionally protects peers with longer connect time to prevent attacks that start later. The process does not check `versions` explicitly.
