### ISSUE TITLE
More detailed P2PPeerInfo

### ISSUE THREAD

**Issue by jondubois** [LiskHQ/lisk-sdk#4313]
### Description

Currently, `P2PPeerInfo` (which we keep in the `PeerBook`) only holds information about a peer which we can share with other peers. There should also be a way to store information about a peer which the node wants to keep only for its own private use. For example: A peer's `reputation` and `productivity` should not be shared with other peers.

### Motivation

Being able to track private information about a peer on a `P2PPeerInfo` instance will open up the following opportunities:

- Allows a peer's state to be tracked across multiple connections over time. If a peer connects to our node or we connect to them, instead of creating a new `Peer` instance from scratch with a fresh `reputation` and `productivity` score, the `P2PPeerInfo` from the `PeerBook` could be used to initialize the `Peer` instance based on the last known `reputation` and `productivity` for that peer.

- The internal P2P library API has a `p2p.getConnectedPeers()` method which exposes `P2PPeerInfo` objects; it would be useful for these `P2PPeerInfo` objects include as much info about the peer as possible; then it could be used to get detailed information about the network from the node's perspective.

### Acceptance Criteria

Based on an internal poll, the P2P team voted to follow this format for the new `P2PPeerInfo` interface:

`interface P2PPeerInfo {sharedState: P2PSharedState, internalState: P2PInternalState}`

What is currently referred to as `P2PPeerInfo` in the current code (which a node shares with other peers) should be renamed to `P2PSharedState`. The new `P2PPeerInfo` then becomes the combination of the `sharedState` and `internalState` so it encapsulates complete information about the peer.

Note that the step of backing up the `P2PPeerInfo` inside the `PeerBook` and then restoring it when the peer reconnects is outside the scope of this issue.

**Comment by jondubois** [comment]
Also, something to think about and discuss is whether we should store the `kind` of the peer in the `P2PPeerInfo -> P2PInternalState` as well; this would refer to the last known peer `kind` (`inbound` or `outbound`).

**Comment by ishantiw** [comment]
Since we are using `ipAddress` , `wsPort` and `peerId` and also it doesn't qualify as a state of a peer but more like the identity of a peer that should not change. We have come up with below interface,

```
interface P2PPeerInfo {peerId: string, ipAddress: string, wsPort: number, 
                                       sharedState: P2PSharedState,
                                       internalState: P2PInternalState}
```

- **sharedState**: This field will store different values of a peer that are communicated across the network. Also, removing height value as a mandatory field from it.

- **internalState**: This field will be an object holding values related to internal management of a peer and be more stateful about a peer so that we don't lose valuable information for performance and productivity once we disconnected with them. As of now all the fields are optional but it will be fully implemented and used in across the library in the issue #4314
