### ISSUE TITLE
Replace the usage of _lastBlock with getter lastBlock

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#4772]
### Description
In the `lisk-chain` library we are using `this._lastBlock` for referring to the last block of the blockchain(local node).
### Motivation
After the implementation of #4709 the `lisk-chain` library can refer to blocks cache for the last block directly `this.dataAccess.getLastBlockHeader`
### Acceptance Criteria
- Replace the usage of `this._lastBlock` with getter `this.lastBlock` which will return `this.dataAccess.getLastBlockHeader` everywhere in `lisk-chain` and other libraries
- Update tests to not use `this._lastBlock` but to mock the `this.lastBlock` getter to return the desired results

**Comment by nazarhussain** [comment]
Currently `_lastBlock` is set only on four places: 

1. In lisk-chain constructor set to genesis block 
2. In lisk-chain init set to last block in database
3. In lisk-chain save method
4. In lisk-chain remove method 

I think these four usages are pretty much obvious and manageable. If we replace `_lastBlock` with data access call it will turn out to be an asynchronous call. Although internally it doe not make any I/O due to cache but semantically all usages will look like as its doing some I/O. 

Additionally `tip of the chain` or `lastBlock` been property of the `lisk-chain` is more understandable and it should be treated as property. As discussed with @shuse2 don't see any value in refactoring `lastBlock` and converting it to `async getLastBlock`. If one want to or had use `dataAccess` they can, but `lastBlock` as property of the chain should still remain there.
