### ISSUE TITLE
ReadError: Database is not open

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#5851]
### Expected behavior

In case of any error in loading or execution of any logic, the application must cleanup and exit successfully. 

### Actual behavior

If we have any issue in the plugin loading logic then application crashes with above error. 

### Steps to reproduce

```
class MyPlugin extends BasePlugin {
    myAttribute = undefined. 

    // all required interfaces and attributes 


   async load(channel) {
       channel.subscribe('app:ready', () => { 
           this.myAttribute = options.myAttribute; // options does not exists. 
       });
   }
}
```

### Which version(s) does this affect? (Environment, OS, etc...)
5.0.0

**Comment by shuse2** [comment]
Node initialization started, but at the same time shutdown process has been triggered, which closes the database while it's been used
This requires initalization process refactoring

**Comment by pablitovicente** [comment]
After looking at this the issue happens because the way plugins are currently written; they are using the event `app:ready` as part of their loading mechanism, possibly to try to make sure RPC  can be used, so error happens after the application is already starting the loading of delegates while at the same time the error happens in a broken plugin.

As we are now awaiting for initialisation in `public async run()` we no longer need to depend on an event in the `load()` method in plugins

**Comment by nazarhussain** [comment]
The event `app:ready` is used to make sure all the plugins are loaded. Otherwise one may not sure if an event or action invoked in a plugin are related to `node` or some other plugin.
