### ISSUE TITLE
Decoding won't work in the browser

### ISSUE THREAD

**Issue by corbifex** [LiskHQ/lisk-sdk#6039]
### Expected behavior
Decoding works in the browser.

### Actual behavior
In the browser decoding won't work. eg. client.block.getByHeight(123) gives an error: 

> Uncaught (in promise) Error: Unsupported data:8,2,16,240,135,158,... and format:undefined. Currently only Buffers or hex and utf8 strings are supported.

When it goes through `decodeBlock()` [codec.ts:90](https://github.com/LiskHQ/lisk-sdk/blob/a65b965effabd94d2edc60a5e4a273dec089d7f5/elements/lisk-api-client/src/codec.ts#L90) it's passed as an uint8 array buffer where typeof === object not buffer nor string which are required for the hash() function from lisk-cryptography.

### Steps to reproduce
`const block = await client.block.getByHeight(123);`

### Which version(s) does this affect? (Environment, OS, etc...)
Browser (chrome), lisk-api-client@5.0.0

**Comment by shuse2** [comment]
@corbifex are you using the `@liskhq/lisk-client`?
If you use the `lisk-api-client` directly, it does not include the shim for the Buffer using https://www.npmjs.com/package/buffer
I have checked on  `@liskhq/lisk-client` on browser (chrome), and the `client.block.getByHeight(123)` is working fine

**Comment by corbifex** [comment]
Yes for me `@liskhq/lisk-client` doesn't work in the browser. With the wsChannel fix it loads but block decode won't work see my initial issue. 
Cryptography hash function which you use for hashing ID's won't work in the browser because the buffer works different in the browser.  
I manually fixed it by changing it to `const id = hash(block.header.toString('utf8'), 'utf8');`

**Comment by corbifex** [comment]
I guess my solution is wrong it outputs a wrong id 👎

**Comment by tomploem** [comment]
I also experienced this issue when using `apiClient.createClient(...customChannel)` using the import from `@liskhq/lisk-client`.  I was able to "bypass" the error by modifying the node_modules: 

When diving into the node_modules, `@liskhq/lisk-api-client` does not have a dist-browser folder. I copied the logic to build a browser version similar on how `@liskhq/lisk-client` uses browserify:

1. npm install browserify and buffer
2. add script command: "build:browser": "npm run build:node && npm run browserify"
3. add script command: "browserify": "browserify ./dist-node/index.js -o ./dist-browser/index.js -s lisk"
4. change main entrypoint from `"main": "dist-node/index.js",` to `"main": "dist-browser/index.js"`

I guess that `lisk-client` will always use the dist-node version from `lisk-api-client` because there is no browser version. The API client will then try to use some NodeJS function and result in an error?

**Comment by shuse2** [comment]
For using dist-browser, it is related to below issues.
https://github.com/LiskHQ/lisk-sdk/issues/3348
https://github.com/LiskHQ/lisk-sdk/issues/4163

if i put the browser field, it fails to build the browser.

The buffer usage should be supported by https://github.com/LiskHQ/lisk-sdk/blob/development/elements/lisk-client/src/index.ts#L26-L28.

Adding `Buffer` in the lisk-client is important because it is used across the application everywhere

**Comment by shuse2** [comment]
This should be resolved by #6049
