### ISSUE TITLE
Errors compiling project with skipLibCheck disabled

### ISSUE THREAD

**Issue by Lemii** [LiskHQ/lisk-sdk#6108]
### Expected behavior
There should be no compilation errors.

### Actual behavior
When you try to compile a project that contains the `lisk-sdk` package and `skipLibCheck` is disabled in the tsconfig file, the following errors are thrown: 

```
> rimraf ./build && tsc --resolveJsonModule

node_modules/@liskhq/lisk-p2p/dist-node/types.d.ts:1:10 - error TS2724: Module '"../../../@types/socketcluster-server"' has no exported member 'SCServerSocket'. Did you mean 'AGServerSocket'?

1 import { SCServerSocket } from 'socketcluster-server';
           ~~~~~~~~~~~~~~

node_modules/lisk-sdk/dist-node/samples/index.d.ts:1:37 - error TS2498: Module '"/backend/node_modules/lisk-sdk/dist-node/samples/genesis_block_devnet"' uses 'export =' and cannot be used with 'export *'.

1 export * as genesisBlockDevnet from './genesis_block_devnet.json';
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/lisk-sdk/dist-node/samples/index.d.ts:2:31 - error TS2498: Module '"/backend/node_modules/lisk-sdk/dist-node/samples/config_devnet"' uses 'export =' and cannot be used with 'export *'.

2 export * as configDevnet from './config_devnet.json';
```
The compiler will also complain about missing `@types/socketcluster-server` and `@types/lodash.clonedeep` types.

### Steps to reproduce

- Initialize a project with `npm init -y` and `tsc --init`
- Disable `skipLibCheck` in tsconfig
- Create a barebones Lisk blockchain (https://lisk.io/documentation/lisk-sdk/quickstart.html)
- Try to build the project with `tsc`

### Which version(s) does this affect? (Environment, OS, etc...)
```
    "lisk-sdk": "^5.0.3",
    "typescript": "^4.1.3"
```

OS: Ubuntu 18.04

**Comment by shuse2** [comment]
JSON should be resolved in the next release where we use the latest typescript version, and updated the export syntax.

If this option is turned on, it seems like if we use a library which does not have integrated type support, and not add the type definition in the `dependencies`, it will fail since `devDependencies` will not be installed.

I think it make sense not to include the type definition of dependent libraries as `dependencies`.

What is the reason you want to disable `skipLibCheck`?

**Comment by shuse2** [comment]
This is already resolved in the latest release
