### ISSUE TITLE
Problem in running basic lisk tutorials projects 

### ISSUE THREAD

**Issue by 2112akilesh** [LiskHQ/lisk-sdk#6461]
I just clone lisk-sdk-examples from [official repository](https://github.com/LiskHQ/lisk-sdk-examples#supply-chain-lisk-transport) and navigate to `/lisk-sdk-examples/tutorials/hello-world/blockchain_app/` and installed the npm packages then started the application `node index.js` it runs and stops in line`INFO lisk-framework: Loading controller (module=lisk:app)`

<img width="779" alt="node cmd" src="https://user-images.githubusercontent.com/53332156/120888486-2a86f580-c616-11eb-94d6-e5893296e487.png">
<br>
and the ram consumed by the node drastically increased by time after running the application it doesn't stop consuming ram it just increases when time passes.<br>
to stop the application `ctrl + c`  is not working.We should go to the task manager and make the node end task or delete the whole program.

<img width="500" alt="node problem" src="https://user-images.githubusercontent.com/53332156/120888442-f6133980-c615-11eb-81c9-1092bf6d8a66.png">
<br>

**My Configuration**:
> Windows 10
> node version 12.22

**Comment by JesusTheHun** [comment]
Thanks for opening an issue !
Lisk SDK uses Unix Sockets and therefore does not support Windows.

I encourage you to use a Linux with docker or with a VM. 
Or of course if you own a Mac you can use it as well.

**Comment by 2112akilesh** [comment]
Do you have any future plans to work with windows

**Comment by JesusTheHun** [comment]
I'm not part of the project's team, but I discussed the topic a while ago and clearly the answer is no. Unless Windows support Unix Socket, this will never happen.

**Comment by shuse2** [comment]
Thanks for opening the issue. For now, we don't have plan to support windows at least before the interoperability implementation.
As @JesusTheHun mentioned, we have features/code which are not compatible with windows platform at the moment, and it is not easy to mitigate the problem. Therefore, as he says please use VM or docker to run try our SDK.

Although we cannot support it at the moment because we are focused on the interoperability, we will consider the windows compatibility in the future.
