### ISSUE TITLE
Handling of genesis block takes too much time

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#6573]
### Expected behavior

Even with a large genesis block file, it should be able to sync the nodes properly.

### Actual behavior

- Procedure `getHighestCommonBlock` for given block ids returns the whole common block header, in case of testnet or mainnet genesis block header the size of genesis block header is too big (20-200MB).
- When getting the block, it tries to decode the asset which takes long.
- Genesis block are kept in memory

### Steps to reproduce

- Migrate 2.1.6 and generate genesis block (which is around 200MB)
- Run `lisk-core start -n mainnet` with the new genesis block
- Connect to running node as seed peer
- Observer the syncing node fails to request block during synchronisation

### Which version(s) does this affect? (Environment, OS, etc...)
5.1.1, 3.0.0

**Comment by shuse2** [comment]
General direction of solving this issue will be
* lisk-chain package will not decode the block header asset, and it will be encode/decode only when it's needed. (ie: for hooks etc)
* Add genesis data to consensus state (init round and height) so that genesis header is not needed in the memory
* Update getHighestCommonBlock to return only ID of the common block
