### ISSUE TITLE
Implement endpoints for token module

### ISSUE THREAD

**Issue by nagdahimanshu** [LiskHQ/lisk-sdk#7414]
### Description

Implement endpoints for token module
There is need to implement similar endpoint like `getTotalSupply` to retrieve `stakedLSK`, `inflationRate` and `totalSupplyLSK `
This information can be included in blockchain application stats endpoint response by `lisk-service`.

Endpoints:

- getStakedLSK
- getInflationRate
- totalSupplyLSK

### Acceptance Criteria

- Suggested endpoint is added to token module
- Add unit test for all the endpoints

**Comment by shuse2** [comment]
`getInflationRate`, we can include the endpoint with #7622 which will be exposed under `reward` module

`getStakedLSK`, I think this will go under DPoS, but since this will require to iterate through all the votes, I don't think we can expose this value from endpoint

totalSupply is already exposed by token module `getTotalSupply`, if LSK specifically from sidechain, i don't think sidechain can know the total supply of LSK.

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
