### ISSUE TITLE
Deprecating numeric id's 

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-sdk#742]
1.0.0 - will be quite major hardfork, why not move then:

- Numeric block id based on hash, simply to it's hash
- Transaction id based on hash, simply to it's hash
- Address to Ripedm160+b58 like bitcoin

To prevent collisions with numeric shortcuts which are much more prone to collisions, especially with [this algorithm.](https://github.com/LiskHQ/lisk-js/blob/development/src/transactions/crypto.js#L350)

Changing ids and addresses will cause problem for exchanges and other services, however there is simple solution for that - let there be both implementations of ids, new one will be enforced from 1.0.0 or after N block.  Addresses already written down to blockchain could be used with both aliases (numeric shortcut and r160+b58) and same goes for tx and block id's - older blocks/tx can be retrieved with numeric shortcuts and hash, while new one only hash.

Sooner - better.

**Comment by 4miners** [comment]
@karek314 That is already planned, but not for 1.0.0 release.

**Comment by shuse2** [comment]
Closing this issue since it will be addressed in Network Longevity with
[LIP-0010](https://github.com/LiskHQ/lips/blob/master/proposals/lip-0010.md), [LIP-0018](https://github.com/LiskHQ/lips/blob/master/proposals/lip-0018.md), [LIP-0019](https://github.com/LiskHQ/lips/blob/master/proposals/lip-0019.md),
