### ISSUE TITLE
Add additional validation to config parameters

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#8465]
### Description

Add additional range validation for the genesis config and module configs as below

#### Genesis

| Property | Min | Max |
|----------|-----|-----|
|      bftBatchSize    | n/a    |   MAX_NUM_VALIDATORS+2  |
|       blockTime   |  3 (tentative value)   |   `30*24*60*60` 1 block per month  |
|       maxTransactionsSize   |  MAX_CCM_SIZE + some buffer   |   30*1024 (should be benchmarked)  |

#### PoS
| Property | Min | Max |
|----------|-----|-----|
|      numberActiveValidators    | 1    |   MAX_NUM_VALIDATORS  |
|       numberStandbyValidators   |  0   |   2  |
|       factorSelfStakes   |  1   |   MAX_UINT32  |
|      maxLengthName    | 10   | 30   |
|     maxNumberSentStakes     |  1  |  20  |
|    maxNumberPendingUnlocks      |  1  |  40  |
|     failSafeMissedBlocks     |   2 | MAX_UINT64   |
|      failSafeInactiveWindow    | 432000/BLOCK_TIME   | 31536000/BLOCK_TIME   |
|     punishmentWindow     |  432000/BLOCK_TIME   | 31536000/BLOCK_TIME  |
|     minWeightStandby     |  1   | MAX_UINT64 |
|     validatorRegistrationFee     |  0   | MAX_UINT64 |
|     maxBFTWeightCap     |  300   | 10000 |
|     commissionIncreasePeriod     |  100   | 10000 |
|     maxCommissionIncreaseRate     |  0   | MAX_UINT64 |

##### Additional properties which are currently not configurable

- PUNISHMENT_WINDOW_STAKING
- PUNISHMENT_WINDOW_SELF_STAKING
- LOCKING_PERIOD_STAKING
- LOCKING_PERIOD_SELF_STAKING
- BASE_STAKE_AMOUNT
- WEIGHT_SCALE_FACTOR
- REPORT_MISBEHAVIOR_REWARD
- REPORT_MISBEHAVIOR_LIMIT_BANNED

### Acceptance Criteria
- Validation for above configuration are added along with test

**Comment by bobanm** [comment]
This issue will be resolved with the following 5 updates to the original description:

1. As agreed with @gkoumout and @ricott1, the `some buffer` value should be 1024 bytes.
2. Parameter `commissionIncreasePeriod` had validation range of `100..10000`, and `maxCommissionIncreaseRate` `0..MAX_UINT64`. That is obviously a typo, because `100..10000` are the values for `maxCommissionIncreaseRate` instead, and I will swap the ranges for those 2 params.
3. Since `BLOCK_TIME` is not a constant, but a configurable parameter, it is not a good idea to include it in schema validation. @ishantiw proposed to handle validation during `PoSModule.init()` and it is handled in #8694.
4. For `uintxx` types, the value range is implicitly `0..MAX_UINTxx`, so there is no need to explicitly add them to the schema.
5. The 8 constants listed at the end of the issue under section "Additional properties which are currently not configurable" have been included by mistake and are out of scope of this issue.
